version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: "node-gmp-db"
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=node_gmp
            - MONGO_INITDB_ROOT_PASSWORD=password123
            - MONGO_INITDB_DATABASE=node_gmp
        image: mongo
